// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq_zhUtk8X3aOvMkfpyqe8_B6l0Pa-Azw',
    appId: '1:545739297550:web:12a3df019ff243e2f7bd5f',
    messagingSenderId: '545739297550',
    projectId: 'scrapchef-bf262',
    authDomain: 'scrapchef-bf262.firebaseapp.com',
    storageBucket: 'scrapchef-bf262.firebasestorage.app',
    measurementId: 'G-GS4CBRK6QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_kAOO0qWGBNkCMr35wcs4e-nW3GQrEBo',
    appId: '1:545739297550:android:3f45b8552b86dc41f7bd5f',
    messagingSenderId: '545739297550',
    projectId: 'scrapchef-bf262',
    storageBucket: 'scrapchef-bf262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV0jPvpxJpzzXDxQdps33ipYP0qM_xx1k',
    appId: '1:545739297550:ios:34d617939a15f5bef7bd5f',
    messagingSenderId: '545739297550',
    projectId: 'scrapchef-bf262',
    storageBucket: 'scrapchef-bf262.firebasestorage.app',
    iosBundleId: 'com.example.scrapChef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV0jPvpxJpzzXDxQdps33ipYP0qM_xx1k',
    appId: '1:545739297550:ios:34d617939a15f5bef7bd5f',
    messagingSenderId: '545739297550',
    projectId: 'scrapchef-bf262',
    storageBucket: 'scrapchef-bf262.firebasestorage.app',
    iosBundleId: 'com.example.scrapChef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq_zhUtk8X3aOvMkfpyqe8_B6l0Pa-Azw',
    appId: '1:545739297550:web:a704d9f7a0d944cdf7bd5f',
    messagingSenderId: '545739297550',
    projectId: 'scrapchef-bf262',
    authDomain: 'scrapchef-bf262.firebaseapp.com',
    storageBucket: 'scrapchef-bf262.firebasestorage.app',
    measurementId: 'G-X19K3Q320T',
  );

}