// This file is generated by Firebase CLI. For now, a placeholder is provided.
// Run: `flutterfire configure` after adding firebase to your project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TODO_REPLACE_WITH_ANDROID_API_KEY',
    appId: 'TODO_REPLACE_WITH_ANDROID_APP_ID',
    messagingSenderId: 'TODO_REPLACE_WITH_MESSAGING_SENDER_ID',
    projectId: 'TODO_REPLACE_WITH_PROJECT_ID',
    storageBucket: 'TODO_REPLACE_WITH_STORAGE_BUCKET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO_REPLACE_WITH_IOS_API_KEY',
    appId: 'TODO_REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: 'TODO_REPLACE_WITH_MESSAGING_SENDER_ID',
    projectId: 'TODO_REPLACE_WITH_PROJECT_ID',
    storageBucket: 'TODO_REPLACE_WITH_STORAGE_BUCKET',
  );
}
